// Auto-generated from free-tex-packer-core (MIT License)
// Templates adapted for browser-side Mustache rendering

export interface ExportFormat {
  id: string;
  label: string;
  group: string;
  fileExt: string;
  template: string;
}

const T_JSON_ARRAY = `{
  "frames": [
    {{#rects}}
    {
      "filename": "{{{name}}}",
      "frame": { "x": {{frame.x}}, "y": {{frame.y}}, "w": {{frame.w}}, "h": {{frame.h}} },
      "rotated": {{rotated}},
      "trimmed": {{trimmed}},
      "spriteSourceSize": { "x": {{spriteSourceSize.x}}, "y": {{spriteSourceSize.y}}, "w": {{spriteSourceSize.w}}, "h": {{spriteSourceSize.h}} },
      "sourceSize": { "w": {{sourceSize.w}}, "h": {{sourceSize.h}} }
    }{{^last}},{{/last}}
    {{/rects}}
  ],
  "meta": { "app": "SpriteForge", "version": "1.0", "image": "{{config.imageName}}", "format": "RGBA8888", "size": { "w": {{config.imageWidth}}, "h": {{config.imageHeight}} }, "scale": 1 }
}`;

const T_JSON_HASH = `{
  "frames": {
    {{#rects}}
    "{{{name}}}": {
      "frame": { "x": {{frame.x}}, "y": {{frame.y}}, "w": {{frame.w}}, "h": {{frame.h}} },
      "rotated": {{rotated}},
      "trimmed": {{trimmed}},
      "spriteSourceSize": { "x": {{spriteSourceSize.x}}, "y": {{spriteSourceSize.y}}, "w": {{spriteSourceSize.w}}, "h": {{spriteSourceSize.h}} },
      "sourceSize": { "w": {{sourceSize.w}}, "h": {{sourceSize.h}} }
    }{{^last}},{{/last}}
    {{/rects}}
  },
  "meta": { "app": "SpriteForge", "version": "1.0", "image": "{{config.imageName}}", "format": "RGBA8888", "size": { "w": {{config.imageWidth}}, "h": {{config.imageHeight}} }, "scale": 1 }
}`;

const T_PHASER3 = `{
  "textures": [{
    "image": "{{config.imageName}}", "format": "RGBA8888",
    "size": { "w": {{config.imageWidth}}, "h": {{config.imageHeight}} }, "scale": 1,
    "frames": [
      {{#rects}}
      {
        "filename": "{{{name}}}", "rotated": {{rotated}}, "trimmed": {{trimmed}},
        "sourceSize": { "w": {{sourceSize.w}}, "h": {{sourceSize.h}} },
        "spriteSourceSize": { "x": {{spriteSourceSize.x}}, "y": {{spriteSourceSize.y}}, "w": {{spriteSourceSize.w}}, "h": {{spriteSourceSize.h}} },
        "frame": { "x": {{frame.x}}, "y": {{frame.y}}, "w": {{frame.w}}, "h": {{frame.h}} }
      }{{^last}},{{/last}}
      {{/rects}}
    ]
  }],
  "meta": { "app": "SpriteForge", "version": "1.0" }
}`;

const T_CSS = `/* Generated by SpriteForge */
.sprite { display:inline-block; background-image:url('{{config.imageName}}'); background-repeat:no-repeat; }
{{#rects}}
.sprite-{{{cssName}}} { width:{{frame.w}}px; height:{{frame.h}}px; background-position:-{{frame.x}}px -{{frame.y}}px; }
{{/rects}}`;

const T_SPINE = `
{{config.imageName}}
size: {{config.imageWidth}},{{config.imageHeight}}
format: RGBA8888
filter: Nearest,Nearest
repeat: none
{{#rects}}
{{{name}}}
  rotate: {{rotated}}
  xy: {{frame.x}},{{frame.y}}
  size: {{frame.w}},{{frame.h}}
  orig: {{sourceSize.w}},{{sourceSize.h}}
  offset: 0,0
  index: -1
{{/rects}}`;

const T_STARLING = `<?xml version="1.0" encoding="UTF-8"?>
<TextureAtlas imagePath="{{config.imageName}}" width="{{config.imageWidth}}" height="{{config.imageHeight}}">
  {{#rects}}
  <SubTexture name="{{{name}}}" x="{{frame.x}}" y="{{frame.y}}" {{#rotated}}width="{{frame.h}}" height="{{frame.w}}" rotated="true"{{/rotated}}{{^rotated}}width="{{frame.w}}" height="{{frame.h}}"{{/rotated}} frameX="-{{spriteSourceSize.x}}" frameY="-{{spriteSourceSize.y}}" frameWidth="{{sourceSize.w}}" frameHeight="{{sourceSize.h}}"/>
  {{/rects}}
</TextureAtlas>`;

const T_UNITY = `:format=40300
:texture={{config.imageName}}
:size={{config.imageWidth}}x{{config.imageHeight}}
:pivotpoints=enabled
:borders=disabled
{{#rects}}
{{{escapedName}}};{{frame.x}};{{mirrorY}};{{frame.w}};{{frame.h}}; 0.5;0.5; 0;0;0;0
{{/rects}}`;

const T_GODOT = `[gd_resource type="AtlasTexture" load_steps={{loadSteps}} format=3]

[ext_resource type="Texture2D" path="res://{{config.imageName}}" id="1"]
{{#rects}}

[sub_resource type="AtlasTexture" id="{{subId}}"]
atlas = ExtResource("1")
region = Rect2({{frame.x}}, {{frame.y}}, {{frame.w}}, {{frame.h}})
# {{{name}}}
{{/rects}}`;

const T_GODOT_TILESET = `{
\t"textures": [{
\t\t"image": "{{config.imageFile}}", "size": { "w": {{config.imageWidth}}, "h": {{config.imageHeight}} },
\t\t"sprites": [
\t\t\t{{#rects}}
\t\t\t{ "filename": "{{{name}}}", "region": { "x": {{frame.x}}, "y": {{frame.y}}, "w": {{frame.w}}, "h": {{frame.h}} }, "margin": { "x": 0, "y": 0, "w": 0, "h": 0 } }{{^last}},{{/last}}
\t\t\t{{/rects}}
\t\t]
\t}],
\t"meta": { "app": "SpriteForge", "version": "1.0", "format": "RGBA8888" }
}`;

const T_UNREAL = `{
  "frames": {
    {{#rects}}
    "{{{name}}}": {
      "frame": { "x": {{frame.x}}, "y": {{frame.y}}, "w": {{frame.w}}, "h": {{frame.h}} },
      "rotated": {{rotated}}, "trimmed": {{trimmed}},
      "spriteSourceSize": { "x": {{spriteSourceSize.x}}, "y": {{spriteSourceSize.y}}, "w": {{spriteSourceSize.w}}, "h": {{spriteSourceSize.h}} },
      "sourceSize": { "w": {{sourceSize.w}}, "h": {{sourceSize.h}} }
    }{{^last}},{{/last}}
    {{/rects}}
  },
  "meta": { "app": "SpriteForge", "version": "1.0", "image": "{{config.imageName}}", "format": "RGBA8888", "size": { "w": {{config.imageWidth}}, "h": {{config.imageHeight}} }, "scale": 1, "target": "paper2d" }
}`;

const T_UIKIT = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>frames</key><dict>
    {{#rects}}
    <key>{{{name}}}</key><dict>
      <key>x</key><real>{{frame.x}}</real><key>y</key><real>{{frame.y}}</real>
      <key>w</key><real>{{frame.w}}</real><key>h</key><real>{{frame.h}}</real>
      <key>oX</key><real>{{spriteSourceSize.x}}</real><key>oY</key><real>{{spriteSourceSize.y}}</real>
      <key>oW</key><real>{{sourceSize.w}}</real><key>oH</key><real>{{sourceSize.h}}</real>
    </dict>
    {{/rects}}
  </dict>
  <key>meta</key><dict>
    <key>image</key><string>{{config.imageName}}</string>
    <key>width</key><integer>{{config.imageWidth}}</integer>
    <key>height</key><integer>{{config.imageHeight}}</integer>
  </dict>
</dict>
</plist>`;

const T_EGRET2D = `{
    "file": "{{config.imageName}}",
    "frames": {
        {{#rects}}
        "{{{name}}}": { "x": {{frame.x}}, "y": {{frame.y}}, "w": {{frame.w}}, "h": {{frame.h}}, "hw": {{frame.hw}}, "hh": {{frame.hh}} }{{^last}},{{/last}}
        {{/rects}}
    }
}`;

const T_XML = `<?xml version="1.0" encoding="UTF-8"?>
<TextureAtlas imagePath="{{config.imageName}}" width="{{config.imageWidth}}" height="{{config.imageHeight}}" scale="1" format="RGBA8888">
  {{#rects}}
  <sprite n="{{{name}}}" x="{{frame.x}}" y="{{frame.y}}" w="{{frame.w}}" h="{{frame.h}}" pX="0.5" pY="0.5"{{#trimmed}} oX="{{spriteSourceSize.x}}" oY="{{spriteSourceSize.y}}" oW="{{sourceSize.w}}" oH="{{sourceSize.h}}"{{/trimmed}}{{#rotated}} r="y"{{/rotated}}/>
  {{/rects}}
</TextureAtlas>`;

const T_COCOS2D = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>frames</key><dict>
    {{#rects}}
    <key>{{{name}}}</key><dict>
      <key>frame</key><string>{{&lbrace}}{{frame.x}},{{frame.y}}{{&rbrace}},{{&lbrace}}{{frame.w}},{{frame.h}}{{&rbrace}}</string>
      <key>offset</key><string>{{&lbrace}}{{offsetX}},{{offsetY}}{{&rbrace}}</string>
      <key>rotated</key><{{rotated}}/>
      <key>sourceColorRect</key><string>{{&lbrace}}{{spriteSourceSize.x}},{{spriteSourceSize.y}}{{&rbrace}},{{&lbrace}}{{spriteSourceSize.w}},{{spriteSourceSize.h}}{{&rbrace}}</string>
      <key>sourceSize</key><string>{{&lbrace}}{{sourceSize.w}},{{sourceSize.h}}{{&rbrace}}</string>
    </dict>
    {{/rects}}
  </dict>
  <key>metadata</key><dict>
    <key>format</key><integer>2</integer>
    <key>pixelFormat</key><string>RGBA8888</string>
    <key>premultiplyAlpha</key><false/>
    <key>size</key><string>{{&lbrace}}{{config.imageWidth}},{{config.imageHeight}}{{&rbrace}}</string>
    <key>textureFileName</key><string>{{config.imageName}}</string>
  </dict>
</dict>
</plist>`;

export const EXPORT_FORMATS: ExportFormat[] = [
  { id: "json", label: "JSON Array (Generic)", group: "JSON", fileExt: "json", template: T_JSON_ARRAY },
  { id: "json-hash", label: "JSON Hash", group: "JSON", fileExt: "json", template: T_JSON_HASH },
  { id: "pixijs", label: "PixiJS JSON Hash", group: "PixiJS", fileExt: "json", template: T_JSON_HASH },
  { id: "phaser", label: "Phaser 3", group: "Phaser", fileExt: "json", template: T_PHASER3 },
  { id: "css", label: "CSS Sprites", group: "CSS", fileExt: "css", template: T_CSS },
  { id: "spine", label: "Spine Atlas", group: "Spine", fileExt: "atlas", template: T_SPINE },
  { id: "starling", label: "Starling XML", group: "Starling", fileExt: "xml", template: T_STARLING },
  { id: "unity", label: "Unity3D", group: "Unity", fileExt: "tpsheet", template: T_UNITY },
  { id: "godot", label: "Godot Atlas (.tres)", group: "Godot", fileExt: "tres", template: T_GODOT },
  { id: "godot-tileset", label: "Godot Tileset", group: "Godot", fileExt: "tpset", template: T_GODOT_TILESET },
  { id: "unreal", label: "Unreal Paper2D", group: "Unreal", fileExt: "paper2dsprites", template: T_UNREAL },
  { id: "uikit", label: "iOS UIKit plist", group: "UIKit", fileExt: "plist", template: T_UIKIT },
  { id: "cocos2d", label: "Cocos2d plist", group: "Cocos2d", fileExt: "plist", template: T_COCOS2D },
  { id: "egret2d", label: "Egret2D", group: "Egret2D", fileExt: "json", template: T_EGRET2D },
  { id: "xml", label: "Generic XML", group: "XML", fileExt: "xml", template: T_XML },
];

/** Format IDs available on the FREE tier */
export const FREE_FORMAT_IDS = new Set(["json", "json-hash", "css"]);

export function isFormatFree(id: string): boolean {
  return FREE_FORMAT_IDS.has(id);
}

export function getFormatById(id: string): ExportFormat | undefined {
  return EXPORT_FORMATS.find((f) => f.id === id);
}

export function getFormatGroups(): { group: string; formats: ExportFormat[] }[] {
  const groups = new Map<string, ExportFormat[]>();
  for (const fmt of EXPORT_FORMATS) {
    if (!groups.has(fmt.group)) groups.set(fmt.group, []);
    groups.get(fmt.group)!.push(fmt);
  }
  return Array.from(groups.entries()).map(([group, formats]) => ({ group, formats }));
}
